### ISSUE TITLE
Image saved with border

### ISSUE THREAD

**Issue by Matancy** [NicolasDurant/stick_it#4]
Hi !

I'm using Stick it and the system works quite well.
The problem that I have is that the saved image contains transparent borders, because it seems to perform a screenshot (the view contains border caused by image ratio that can't fit into the screen).

What could be the solution to remove these borders ? 

Thanks !

**Comment by NicolasDurant** [comment]
Hey @Matancy, sorry for the late reply.

Could you show me how you implemented the component in your screen and an example image that is giving you troubles?
I'm not the original owner of the package, just implemented it to be useable with null-safety. Nevertheless I can take a look, if I can reproduce your issue.

**Comment by Matancy** [comment]
Hi @NicolasDurant 

I think that the problem is that the capture done with the stickers is made with the size of the window (phone in my case) and not with the image size. If the image don't fully cover the window, the result will have invisible borders.
The first illustration shows an image that does not fit correctly in the window (it comes from photo camera)

The second illustration shows on 1 the image that came from stick it, and the 2 is an other image displayed with the same rules (border radius). As you can see, the 1 does not have the rounded corners, because the rounded corners are applied on the invisible section (as you can find on a PNG).

![Screenshot_20230403-202424_2](https://user-images.githubusercontent.com/24440469/229596894-44a7153d-9201-482e-95e9-4a3c410a6b49.png)
![Screenshot_20230403-202524_2](https://user-images.githubusercontent.com/24440469/229596904-4ccedfe2-377f-4fee-b8eb-328d6dc9d860.png)

For my code, this is the widget displayed : 
```
Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: const Color.fromRGBO(41, 50, 57, 1),
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios),
          onPressed: () {
            Navigator.pop(context);
          },
        ),
      ),
      body: Stack(
        children: [
          stickIt = StickIt(
            panelHeight: 100,
            child: Image.file(File(widget.background)),
            stickerSize: 150,
            devicePixelRatio: MediaQuery.of(context).devicePixelRatio,
            stickerList: [
              Image.asset('assets/img.png'),
            ],
          ),
          Padding(
            padding:
                EdgeInsets.only(top: MediaQuery.of(context).size.height - 170),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                isLoading
                    ? const CircularProgressIndicator()
                    : RoundedButtonWidget(
                        "Envoyer",
                        null,
                        EdgeInsets.zero,
                        () => sendImage(),
                        true,
                      ),
              ],
            ),
          ),
        ],
      ),
    );
```

And this is the function used to save the image : 

```
Future<void> sendImage() async {
    final imageList = await getImageList();
    final image = await stickIt.exportImage();
    final directory = await getApplicationDocumentsDirectory();
    final path = directory.path;
    final uniqueIdentifier = DateTime.now().millisecondsSinceEpoch;
    File file = await new File('$path/$uniqueIdentifier.png').create();

    file.writeAsBytesSync(image);

    Navigator.of(context).push(
      MaterialPageRoute(
        builder: (context) => DisplayRecapUploadScreen(),
      ),
    );
  }
}
```

I remove some code into the function (code not related to stick it).

Thanks for you help !

**Comment by NicolasDurant** [comment]
Hey, so I took a deeper look yesterday at what is going on.

In short: the author never intended this to fit to the widget size you are providing, meaning, if the `StickIt` class is given a space of let's say 500px by 200px in your layout, then the stickers will always be applicable in that area. If you provide an image that is just 100x100px as background, you will still get 500x200 images as result, because you can lay the stickers over and outside the image boundaries and those stickers still need to be "screenshotted". So, in that sense, I feel like the intended purpose is correct.

Possible solutions:

1. A simple fix would be to make your Image extend to the box size no matter what, in your screen. This will of course result in some stretches or cutoffs of the original image and might not suit your case, but wouldn't result in transparent borders.:
```
body: Stack(
        children: [
          stickIt = StickIt(
            panelHeight: 100,
            child: Image.file(File(widget.background)),  <-- add fit: BoxFit.cover
            stickerSize: 150,
            devicePixelRatio: MediaQuery.of(context).devicePixelRatio,
            stickerList: [
              Image.asset('assets/img.png'),
            ],
          ),
```

2. The following would be a more hacky approach, since you have to rewrite how the widget works. Because the original package was not intended to just make a screenshot of the widget size you are providing, I won't add this as update to the package. You can copy these two files into your project and rename the classes https://github.com/NicolasDurant/stick_it/tree/main/lib/src to whatever you like, and use them as you do with any local widget you are coding. Then you have to do the following adjustments:

- https://github.com/NicolasDurant/stick_it/blob/c970cab6c2cbff1a096aeafeb759ed28773b78cf/lib/src/stick_it.dart#L119 remove the `Expanded`, which allows it to take all available space
- https://github.com/NicolasDurant/stick_it/blob/c970cab6c2cbff1a096aeafeb759ed28773b78cf/lib/src/stick_it.dart#L123, https://github.com/NicolasDurant/stick_it/blob/c970cab6c2cbff1a096aeafeb759ed28773b78cf/lib/src/stick_it.dart#L133 remove the `StackFit.expand` in both places
- Now you have to tell the `RepaintBoundary` how much space it is allowed to take via a child Container, this would need to be your provided image size
- The result should look something like this
```
Column(
      children: <Widget>[
        RepaintBoundary(
          key: key,
          child: Container( <- shrinks the RepaintBoundary and therefore the area of the screenshot
            height: 100, <- should be the calculated height of ur image, that you need to pass via the class
            width: 100, <- should be the calculated width of ur image, that you need to pass via the class
            child: Stack(
              children: <Widget>[
                LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                    viewport = Size(constraints.maxWidth, constraints.maxWidth);
                    return widget.source;
                  },
                ),
                Stack(
                  children: attachedList,
                )
              ],
            ),
          ),
        ),
```
I have made a visualisation that might help you, if you need to make further tweaks of your own. You have a RepaintBoundary that makes the screenshot and as you suspected is the whole available space, since the columns and stacks always take the most available space. Since there are two layers, the underlying image and the stickers on top, even if your image is smaller than the available space, the sticker layer will take the space and therefore the RepaintBoundary will make a screenshot of the whole view.

![20230405_stickit](https://user-images.githubusercontent.com/28596039/230016143-f0558c20-7623-4d6d-8455-a5d4ebf4a281.jpg)
